module tachy.generate;

/**
 * The `generate` command — scaffolding created on the controller:
 *
 *  - `tachy generate key <path>`: a new age key pair, produced by the
 *    `age-keygen` binary and written to <path> (mode 0600, never
 *    overwritten; the public key is printed). The identity file
 *    decrypts `{ age = ... }` inventory vars — pass it with
 *    `--identity <path>` or `AGE_IDENTITY`, and encrypt secrets with
 *    the printed public key (`age -r <pubkey> -o secret.age`).
 *  - `tachy generate task <path>`: a commented sample tasks file,
 *    loadable as-is (verified by unittest).
 */
import std.stdio : stdout;

import tachy.errors;

/// Dispatch `tachy generate <what> <path>`; returns the exit code.
int runGenerate(in string[] args)
{
    if (args.length != 2)
        throw new TachyError("generate: expected 'key <path>', 'task <path>'"
            ~ " or 'settings <path>' — examples: tachy generate key key.txt,"
            ~ " tachy generate task main.toml, tachy generate settings"
            ~ " settings.toml");
    switch (args[0])
    {
        case "key":
            return generateKey(args[1]);
        case "task":
            return generateTask(args[1]);
        case "settings":
            return generateSettings(args[1]);
        default:
            throw new TachyError("generate: unknown thing '" ~ args[0]
                ~ "' to generate (expected 'key', 'task' or 'settings')");
    }
}

/// New age key pair: `age-keygen -o <path>` writes the identity (0600,
/// refusing to overwrite) and prints the public key; both are relayed.
private int generateKey(string path) @trusted
{
    import std.conv : text;
    import std.string : strip;

    if (!path.length)
        throw new TachyError("generate key: expected an output path");
    auto r = executeSafe(["age-keygen", "-o", path]);
    if (r.status != 0)
        throw new TachyError("generate key '" ~ path ~ "': "
            ~ (r.output.strip.length ? r.output.strip
                : "age-keygen exit status " ~ text(r.status)));
    if (r.output.length)
        stdout.write(r.output); // the public key
    stdout.writefln("identity written to %s — decrypts { age = ... } inventory"
        ~ " vars via --identity %s (or AGE_IDENTITY)", path, path);
    return 0;
}

/// `execute` with a clear error when the binary is not installed.
private auto executeSafe(string[] cmd) @trusted
{
    import std.process : execute;
    try
        return execute(cmd);
    catch (Exception e)
        throw new TachyError("cannot run age-keygen: " ~ e.msg
            ~ " — 'generate key' needs the age toolchain on the controller");
}

/// Sample tasks file; refuses to overwrite (generate creates new files).
private int generateTask(string path)
{
    import std.file : exists, write;
    import std.stdio : writefln;

    if (!path.length)
        throw new TachyError("generate task: expected an output path");
    if (exists(path))
        throw new TachyError("generate task: '" ~ path
            ~ "' already exists (generate never overwrites)");
    try
        write(path, sampleTasksToml);
    catch (Exception e)
        throw new TachyError("cannot write '" ~ path ~ "': " ~ e.msg);
    writefln("wrote a sample tasks file to %s — edit it, then try:"
        ~ " tachy check <selection> %s", path, path);
    return 0;
}

/// Sample settings file; refuses to overwrite (generate creates new
/// files).
private int generateSettings(string path)
{
    import std.file : exists, write;
    import std.stdio : writefln;

    if (!path.length)
        throw new TachyError("generate settings: expected an output path");
    if (exists(path))
        throw new TachyError("generate settings: '" ~ path
            ~ "' already exists (generate never overwrites)");
    try
        write(path, sampleSettingsToml);
    catch (Exception e)
        throw new TachyError("cannot write '" ~ path ~ "': " ~ e.msg);
    writefln("wrote a sample settings file to %s — edit the [imports]"
        ~ " search paths, then use [import.\"name\"] in tasks files", path);
    return 0;
}

private immutable string sampleTasksToml = q"[# A tachy tasks file: every managed resource is a table entry
# keyed by its target, and every job is an idempotent "ensure" —
# applying this file twice changes nothing the second time.
# Generated by "tachy generate task"; run it with:
#   tachy apply <selection> <this file>

[vars]
admin = "root"                    # variables, lowest precedence here

[directories."/tmp/tachy-demo"]   # state (default directory; absent),
mode = "0755"                     # mode, owner, group

[files."/tmp/tachy-demo/hello.txt"]
content = "managed by tachy for {{ admin }} on {{ inventory_hostname }}\n"
mode = "0644"                     # content is templated; src copies a
                                  # file verbatim, template renders one;
                                  # owner/group need a privileged user

[execute."demo file exists"]      # a check: a command plus expectations
run = "test -f /tmp/tachy-demo/hello.txt"
                                  # exit_status, output = "..." or
                                  # { contains = "..." } / { matches = "..." }

# Composition: [includes] run before this file's own jobs, [apply]
# after; each entry binds variables for the composed file.
# [includes."base.toml"]
# env = "prod"
]";

private immutable string sampleSettingsToml = q"[# tachy settings — optional, read once at the start of every run.
# Discovery, first found wins: --settings PATH, the TACHY_SETTINGS
# variable, settings.toml in the current directory, then
# ~/.config/tachy/settings.toml. Relative paths below resolve against
# this file's directory; ~ is expanded.

[imports]
# Directories searched for [import] entries that do not resolve
# relative to their defining tasks file, in order; the first existing
# match wins.
paths = [
    # "libs",
    # "~/.config/tachy/imports",
]

[webui]
# Projects offered by "tachy webui" in the browser: a directory is a
# project entered through its main.toml, a plain file is the entry
# point itself.
projects = [
    # "~/Code/site",
]
]";

version (unittest)
{
    import std.algorithm.searching : canFind;
    import std.exception : assertThrown;
    import std.file : exists, mkdirRecurse, readText, rmdirRecurse, tempDir;
    import std.path : buildPath;

    unittest // runGenerate argument validation
    {
        foreach (args; [cast(string[])[], ["key"], ["key", "a", "b"],
            ["cert", "x"]])
        {
            string msg;
            try
            {
                runGenerate(args);
                assert(false, "expected TachyError");
            }
            catch (TachyError e)
                msg = e.msg;
            assert(canFind(msg, "generate"), msg);
        }
        // empty paths are rejected by both generators
        assertThrown!TachyError(runGenerate(["key", ""]));
        assertThrown!TachyError(runGenerate(["task", ""]));
    }

    unittest // generateTask writes a loadable sample and never overwrites
    {
        import tachy.models : loadTasksFile;

        auto dir = buildPath(tempDir, "tachy_generate_ut");
        if (exists(dir)) rmdirRecurse(dir);
        mkdirRecurse(dir);
        scope (exit) rmdirRecurse(dir);

        const string path = buildPath(dir, "main.toml");
        assert(generateTask(path) == 0);
        assert(exists(path));
        assert(canFind(readText(path), "{{ inventory_hostname }}"));

        // the sample is a valid tasks file: it loads like any other
        auto loaded = loadTasksFile(path);
        assert(loaded.jobs.length >= 3);

        // second generation refuses to overwrite
        string msg;
        try
        {
            generateTask(path);
            assert(false, "expected TachyError");
        }
        catch (TachyError e)
            msg = e.msg;
        assert(canFind(msg, "already exists"), msg);
    }

    unittest // generate settings: loadable sample, no overwrite
    {
        import tachy.settings : loadSettings;

        auto dir = buildPath(tempDir, "tachy_generate_settings_ut");
        if (exists(dir)) rmdirRecurse(dir);
        mkdirRecurse(dir);
        scope (exit) rmdirRecurse(dir);

        const string path = buildPath(dir, "settings.toml");
        assert(runGenerate(["settings", path]) == 0);
        auto s = loadSettings(path);
        assert(s.importPaths.length == 0); // entries are commented out
        assert(s.webuiProjects.length == 0); // so are these
        assertThrown!TachyError(runGenerate(["settings", path]));
    }
}
